### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by wuyiwuyaya** [systemfaliure/ASUS-X556UQK-hackintosh#1]
you can add a patch to fix this issue

**Comment by systemfaliure** [comment]
I know but right now it is not a priority for me.
I would love to receive a PR that fixes this.

**Comment by wuyiwuyaya** [comment]
SSDT-GPRW.aml(file mame)
content
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20180427 (64-bit version)(RM)
 * Copyright (c) 2000 - 2018 Intel Corporation
 * 
 * Disassembling to non-symbolic legacy ASL operators
 *
 * Disassembly of iASLacrU8v.aml, Tue Aug 28 17:58:20 2018
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000057 (87)
 *     Revision         0x02
 *     Checksum         0x66
 *     OEM ID           "hack"
 *     OEM Table ID     "GPRW"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20161210 (538317328)
 */
DefinitionBlock ("", "SSDT", 2, "hack", "GPRW", 0x00000000)
{
    External (XPRW, MethodObj)    // 2 Arguments (from opcode)

    Method (GPRW, 2, NotSerialized)
    {
        If (LEqual (0x6D, Arg0))
        {
            Return (Package (0x02)
            {
                0x6D, 
                Zero
            })
        }

        If (LEqual (0x0D, Arg0))
        {
            Return (Package (0x02)
            {
                0x0D, 
                Zero
            })
        }

        Return (XPRW (Arg0, Arg1))
    }
}


add this in clover acpi  patches :
change Method(GPRW,2,N) to XPRW, pair with SSDT-GPRW.aml(comment)  47505257 02(find)  58505257 02(replace)

**Comment by systemfaliure** [comment]
I checked the RehabMan guide related to the Clover hot-patching. 
You don't need to use SSDT-GPRW, you just need to add the ACPI patch and it will work.
Thanks for your report!

**Comment by wuyiwuyaya** [comment]
Will it restart during sleep?
