### ISSUE TITLE
Mojave trackpad

### ISSUE THREAD

**Issue by ntinos97** [systemfaliure/ASUS-X556UQK-hackintosh#6]
Hello i follow some guides and with the help of your guide and your config.plist was able to install mojave, but i don't have working trackpad. Can you help me?

**Comment by systemfaliure** [comment]
Hello,
I'm sorry but I don't have anymore this laptop.
This repository will be archived, feel free to fork and update if you like.

About the trackpad, I suggest to ask for help here:
https://www.tonymacx86.com/threads/voodooi2c-help-and-support.243378/page-131
